package Display_running;
import java.awt.Color;
import javax.swing.JOptionPane;
import Connection.Connection;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author Khairul Rizki
 */
public class form_login extends javax.swing.JFrame{

    private java.sql.Connection conn = new Connection().connect();
    /**
     * Creates new form form_login
     */
    public form_login() {
        String Display_running = javax.swing.UIManager.getSystemLookAndFeelClassName();
        try{
            javax.swing.UIManager.setLookAndFeel(Display_running);
        }catch(Exception e){}
        
        initComponents();
        
        Login();
    }
    
    protected void Login(){
        main_banner.removeAll();
        main_banner.repaint();
        main_banner.revalidate();
        
        main_banner.add(login_banner);
        main_banner.repaint();
        main_banner.revalidate();
        username.requestFocus();
    }
    
    protected void Create(){
        main_banner.removeAll();
        main_banner.repaint();
        main_banner.revalidate();
        
        main_banner.add(create_banner);
        main_banner.repaint();
        main_banner.revalidate();
        nama.requestFocus();
    }
    
    protected void Forgot(){
        main_banner.removeAll();
        main_banner.repaint();
        main_banner.revalidate();
        
        main_banner.add(forgot_banner);
        main_banner.repaint();
        main_banner.revalidate();
        username_forgot.requestFocus();
    }

    protected void reset(){
        username.setText("");
        password.setText("");
        
        nama.setText("");
        new_username.setText("");
        create_new_password.setText("");
        create_acc_code.setText("");
        
        username_forgot.setText("");
        change_new_password.setText("");
        acc_code.setText("");
    }
    
    protected void Close(){
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar dari aplikasi?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(ok == 0){
            dispose();
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yt = new javax.swing.JLabel();
        twt = new javax.swing.JLabel();
        ig = new javax.swing.JLabel();
        web = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        main_banner = new javax.swing.JPanel();
        login_banner = new javax.swing.JPanel();
        area_login = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        set_akses = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        title6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        show_pw = new javax.swing.JLabel();
        button_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        forgot_pw = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        create_banner = new javax.swing.JPanel();
        area_create = new javax.swing.JPanel();
        title11 = new javax.swing.JLabel();
        title12 = new javax.swing.JLabel();
        title13 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        title14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        create_new_password = new javax.swing.JPasswordField();
        show_pw2 = new javax.swing.JLabel();
        create_button = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        title15 = new javax.swing.JLabel();
        create_acc_code = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        new_username = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        title16 = new javax.swing.JLabel();
        back_button1 = new javax.swing.JLabel();
        back_button3 = new javax.swing.JLabel();
        forgot_banner = new javax.swing.JPanel();
        area_forgot = new javax.swing.JPanel();
        title4 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        title8 = new javax.swing.JLabel();
        username_forgot = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        title9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        change_new_password = new javax.swing.JPasswordField();
        show_pw1 = new javax.swing.JLabel();
        change_pw = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        title10 = new javax.swing.JLabel();
        acc_code = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        back_button2 = new javax.swing.JLabel();
        back_button4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        yt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/yt.png"))); // NOI18N
        yt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ytMouseClicked(evt);
            }
        });
        getContentPane().add(yt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));

        twt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/twt.png"))); // NOI18N
        twt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twtMouseClicked(evt);
            }
        });
        getContentPane().add(twt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        ig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/ig.png"))); // NOI18N
        ig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                igMouseClicked(evt);
            }
        });
        getContentPane().add(ig, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        web.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/website.png"))); // NOI18N
        web.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        web.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                webMouseClicked(evt);
            }
        });
        getContentPane().add(web, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/Logo_Kemhan.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        title1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 241, 241));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("BALITBANG KEMHAN RI");
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 500, -1));

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 241, 241));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("SISTEM KEPUTUSAN MUTASI KARYAWAN");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 500, -1));

        main_banner.setBackground(new java.awt.Color(79, 14, 14));
        main_banner.setLayout(new java.awt.CardLayout());

        login_banner.setBackground(new java.awt.Color(79, 14, 14));

        area_login.setBackground(new java.awt.Color(79, 14, 14));

        title2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 241, 241));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Login.");

        title3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        title3.setForeground(new java.awt.Color(255, 241, 241));
        title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title3.setText("Tidak memiliki Akses?");

        set_akses.setBackground(new java.awt.Color(255, 255, 0));
        set_akses.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        set_akses.setForeground(new java.awt.Color(255, 241, 241));
        set_akses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set_akses.setText("Buat Akses");
        set_akses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        set_akses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                set_aksesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                set_aksesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                set_aksesMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                set_aksesMouseReleased(evt);
            }
        });

        title5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title5.setForeground(new java.awt.Color(255, 241, 241));
        title5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title5.setText("Username");

        username.setBackground(new java.awt.Color(79, 14, 14));
        username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        username.setForeground(new java.awt.Color(250, 250, 250));
        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 14, 14), 0, true));
        username.setCaretColor(new java.awt.Color(255, 255, 255));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        title6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title6.setForeground(new java.awt.Color(255, 241, 241));
        title6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title6.setText("Password");

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        password.setBackground(new java.awt.Color(79, 14, 14));
        password.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        password.setForeground(new java.awt.Color(250, 250, 250));
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 14, 14), 0));
        password.setCaretColor(new java.awt.Color(255, 255, 255));
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        show_pw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/show_pw.png"))); // NOI18N
        show_pw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show_pw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_pwMouseClicked(evt);
            }
        });

        button_login.setBackground(new java.awt.Color(79, 14, 40));
        button_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_loginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_loginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button_loginMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 241, 241));
        jLabel1.setText("Login");

        javax.swing.GroupLayout button_loginLayout = new javax.swing.GroupLayout(button_login);
        button_login.setLayout(button_loginLayout);
        button_loginLayout.setHorizontalGroup(
            button_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(button_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(button_loginLayout.createSequentialGroup()
                    .addGap(0, 22, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 23, Short.MAX_VALUE)))
        );
        button_loginLayout.setVerticalGroup(
            button_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(button_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(button_loginLayout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        forgot_pw.setBackground(new java.awt.Color(255, 255, 0));
        forgot_pw.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        forgot_pw.setForeground(new java.awt.Color(255, 241, 241));
        forgot_pw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgot_pw.setText("Lupa Password?");
        forgot_pw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_pw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgot_pwMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgot_pwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgot_pwMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                forgot_pwMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout area_loginLayout = new javax.swing.GroupLayout(area_login);
        area_login.setLayout(area_loginLayout);
        area_loginLayout.setHorizontalGroup(
            area_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(area_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(area_loginLayout.createSequentialGroup()
                        .addComponent(password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(show_pw))
                    .addGroup(area_loginLayout.createSequentialGroup()
                        .addGroup(area_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title2)
                            .addGroup(area_loginLayout.createSequentialGroup()
                                .addComponent(title3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(set_akses))
                            .addComponent(title5)
                            .addComponent(title6))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addGroup(area_loginLayout.createSequentialGroup()
                        .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(forgot_pw)))
                .addContainerGap())
        );
        area_loginLayout.setVerticalGroup(
            area_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2)
                .addGap(18, 18, 18)
                .addGroup(area_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title3)
                    .addComponent(set_akses))
                .addGap(76, 76, 76)
                .addComponent(title5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(title6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(area_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show_pw, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(area_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(forgot_pw, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(button_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/exit_button.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout login_bannerLayout = new javax.swing.GroupLayout(login_banner);
        login_banner.setLayout(login_bannerLayout);
        login_bannerLayout.setHorizontalGroup(
            login_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_bannerLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(login_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_bannerLayout.createSequentialGroup()
                        .addComponent(area_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_bannerLayout.createSequentialGroup()
                        .addComponent(exit)
                        .addContainerGap())))
        );
        login_bannerLayout.setVerticalGroup(
            login_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_bannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(area_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        main_banner.add(login_banner, "card2");

        create_banner.setBackground(new java.awt.Color(79, 14, 14));

        area_create.setBackground(new java.awt.Color(79, 14, 14));

        title11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title11.setForeground(new java.awt.Color(255, 241, 241));
        title11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title11.setText("Buat Akses Baru");

        title12.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        title12.setForeground(new java.awt.Color(255, 241, 241));
        title12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title12.setText("Isilah data dibawah");

        title13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title13.setForeground(new java.awt.Color(255, 241, 241));
        title13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title13.setText("Nama Anda");

        nama.setBackground(new java.awt.Color(79, 14, 14));
        nama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nama.setForeground(new java.awt.Color(250, 250, 250));
        nama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 14, 14), 0, true));
        nama.setCaretColor(new java.awt.Color(255, 255, 255));

        jPanel6.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        title14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title14.setForeground(new java.awt.Color(255, 241, 241));
        title14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title14.setText("Password Baru");

        jPanel7.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        create_new_password.setBackground(new java.awt.Color(79, 14, 14));
        create_new_password.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        create_new_password.setForeground(new java.awt.Color(250, 250, 250));
        create_new_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 14, 14), 0));
        create_new_password.setCaretColor(new java.awt.Color(255, 255, 255));

        show_pw2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/show_pw.png"))); // NOI18N
        show_pw2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show_pw2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_pw2MouseClicked(evt);
            }
        });

        create_button.setBackground(new java.awt.Color(79, 14, 40));
        create_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                create_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                create_buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                create_buttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                create_buttonMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 241, 241));
        jLabel4.setText("Buat Akses");

        javax.swing.GroupLayout create_buttonLayout = new javax.swing.GroupLayout(create_button);
        create_button.setLayout(create_buttonLayout);
        create_buttonLayout.setHorizontalGroup(
            create_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
            .addGroup(create_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(create_buttonLayout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 17, Short.MAX_VALUE)))
        );
        create_buttonLayout.setVerticalGroup(
            create_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(create_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(create_buttonLayout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        title15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title15.setForeground(new java.awt.Color(255, 241, 241));
        title15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title15.setText("Kode Akses");

        create_acc_code.setBackground(new java.awt.Color(79, 14, 14));
        create_acc_code.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        create_acc_code.setForeground(new java.awt.Color(250, 250, 250));
        create_acc_code.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 14, 14), 0, true));
        create_acc_code.setCaretColor(new java.awt.Color(255, 255, 255));
        create_acc_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                create_acc_codeKeyPressed(evt);
            }
        });

        jPanel8.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        new_username.setBackground(new java.awt.Color(79, 14, 14));
        new_username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        new_username.setForeground(new java.awt.Color(250, 250, 250));
        new_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 14, 14), 0, true));
        new_username.setCaretColor(new java.awt.Color(255, 255, 255));

        jPanel9.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        title16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title16.setForeground(new java.awt.Color(255, 241, 241));
        title16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title16.setText("Username Baru");

        javax.swing.GroupLayout area_createLayout = new javax.swing.GroupLayout(area_create);
        area_create.setLayout(area_createLayout);
        area_createLayout.setHorizontalGroup(
            area_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area_createLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(area_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(area_createLayout.createSequentialGroup()
                        .addComponent(create_new_password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(show_pw2))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(create_acc_code)
                    .addComponent(new_username)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(area_createLayout.createSequentialGroup()
                        .addGroup(area_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title11)
                            .addComponent(title12)
                            .addComponent(title13)
                            .addComponent(title14)
                            .addComponent(title15)
                            .addComponent(create_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title16))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        area_createLayout.setVerticalGroup(
            area_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area_createLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title11)
                .addGap(18, 18, 18)
                .addComponent(title12)
                .addGap(35, 35, 35)
                .addComponent(title13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(new_username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(title14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(area_createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show_pw2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(create_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(title15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create_acc_code, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(create_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        back_button1.setBackground(new java.awt.Color(255, 255, 255));
        back_button1.setForeground(new java.awt.Color(255, 255, 255));
        back_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/back_button.png"))); // NOI18N
        back_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_button1MouseEntered(evt);
            }
        });

        back_button3.setBackground(new java.awt.Color(255, 255, 255));
        back_button3.setForeground(new java.awt.Color(255, 255, 255));
        back_button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/exit_button.png"))); // NOI18N
        back_button3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_button3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout create_bannerLayout = new javax.swing.GroupLayout(create_banner);
        create_banner.setLayout(create_bannerLayout);
        create_bannerLayout.setHorizontalGroup(
            create_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_bannerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(back_button1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(back_button3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, create_bannerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(area_create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        create_bannerLayout.setVerticalGroup(
            create_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_bannerLayout.createSequentialGroup()
                .addGroup(create_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(create_bannerLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(back_button1))
                    .addGroup(create_bannerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_button3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(area_create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_banner.add(create_banner, "card3");

        forgot_banner.setBackground(new java.awt.Color(79, 14, 14));

        area_forgot.setBackground(new java.awt.Color(79, 14, 14));

        title4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title4.setForeground(new java.awt.Color(255, 241, 241));
        title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4.setText("Lupa Password?");

        title7.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        title7.setForeground(new java.awt.Color(255, 241, 241));
        title7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title7.setText("Isilah data dibawah");

        title8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title8.setForeground(new java.awt.Color(255, 241, 241));
        title8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title8.setText("Username");

        username_forgot.setBackground(new java.awt.Color(79, 14, 14));
        username_forgot.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        username_forgot.setForeground(new java.awt.Color(250, 250, 250));
        username_forgot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 14, 14), 0, true));
        username_forgot.setCaretColor(new java.awt.Color(255, 255, 255));

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        title9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title9.setForeground(new java.awt.Color(255, 241, 241));
        title9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title9.setText("Password Baru");

        jPanel4.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        change_new_password.setBackground(new java.awt.Color(79, 14, 14));
        change_new_password.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        change_new_password.setForeground(new java.awt.Color(250, 250, 250));
        change_new_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 14, 14), 0));
        change_new_password.setCaretColor(new java.awt.Color(255, 255, 255));

        show_pw1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/show_pw.png"))); // NOI18N
        show_pw1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show_pw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_pw1MouseClicked(evt);
            }
        });

        change_pw.setBackground(new java.awt.Color(79, 14, 40));
        change_pw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        change_pw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                change_pwMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                change_pwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                change_pwMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                change_pwMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                change_pwMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 241, 241));
        jLabel2.setText("Ubah Password");

        javax.swing.GroupLayout change_pwLayout = new javax.swing.GroupLayout(change_pw);
        change_pw.setLayout(change_pwLayout);
        change_pwLayout.setHorizontalGroup(
            change_pwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
            .addGroup(change_pwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(change_pwLayout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 9, Short.MAX_VALUE)))
        );
        change_pwLayout.setVerticalGroup(
            change_pwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(change_pwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(change_pwLayout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        title10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title10.setForeground(new java.awt.Color(255, 241, 241));
        title10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title10.setText("Kode Akses");

        acc_code.setBackground(new java.awt.Color(79, 14, 14));
        acc_code.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        acc_code.setForeground(new java.awt.Color(250, 250, 250));
        acc_code.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(79, 14, 14), 0, true));
        acc_code.setCaretColor(new java.awt.Color(255, 255, 255));
        acc_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                acc_codeKeyPressed(evt);
            }
        });

        jPanel5.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout area_forgotLayout = new javax.swing.GroupLayout(area_forgot);
        area_forgot.setLayout(area_forgotLayout);
        area_forgotLayout.setHorizontalGroup(
            area_forgotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area_forgotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(area_forgotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_forgot)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(area_forgotLayout.createSequentialGroup()
                        .addComponent(change_new_password)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(show_pw1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addGroup(area_forgotLayout.createSequentialGroup()
                        .addGroup(area_forgotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title4)
                            .addComponent(title7)
                            .addComponent(title8)
                            .addComponent(title9)
                            .addComponent(title10)
                            .addComponent(change_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addComponent(acc_code))
                .addContainerGap())
        );
        area_forgotLayout.setVerticalGroup(
            area_forgotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area_forgotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title4)
                .addGap(18, 18, 18)
                .addComponent(title7)
                .addGap(35, 35, 35)
                .addComponent(title8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_forgot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(title9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(area_forgotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show_pw1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(title10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acc_code, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(change_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        back_button2.setBackground(new java.awt.Color(255, 255, 255));
        back_button2.setForeground(new java.awt.Color(255, 255, 255));
        back_button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/back_button.png"))); // NOI18N
        back_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_button2MouseEntered(evt);
            }
        });

        back_button4.setBackground(new java.awt.Color(255, 255, 255));
        back_button4.setForeground(new java.awt.Color(255, 255, 255));
        back_button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/exit_button.png"))); // NOI18N
        back_button4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_button4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_button4MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout forgot_bannerLayout = new javax.swing.GroupLayout(forgot_banner);
        forgot_banner.setLayout(forgot_bannerLayout);
        forgot_bannerLayout.setHorizontalGroup(
            forgot_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgot_bannerLayout.createSequentialGroup()
                .addGroup(forgot_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgot_bannerLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(area_forgot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(forgot_bannerLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(back_button2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back_button4)))
                .addContainerGap())
        );
        forgot_bannerLayout.setVerticalGroup(
            forgot_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgot_bannerLayout.createSequentialGroup()
                .addGroup(forgot_bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgot_bannerLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(back_button2))
                    .addGroup(forgot_bannerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_button4)))
                .addGap(28, 28, 28)
                .addComponent(area_forgot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        main_banner.add(forgot_banner, "card3");

        getContentPane().add(main_banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 410, 570));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/background.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(990, 570));
        background.setMinimumSize(new java.awt.Dimension(990, 570));
        background.setPreferredSize(new java.awt.Dimension(990, 570));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void webMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_webMouseClicked
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://www.kemhan.go.id/balitbang/"));
        } catch (java.net.URISyntaxException | java.io.IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_webMouseClicked

    private void igMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igMouseClicked
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://www.instagram.com/kemhanri/"));
        } catch (java.net.URISyntaxException | java.io.IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_igMouseClicked

    private void twtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twtMouseClicked
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://twitter.com/Kemhan_RI"));
        } catch (java.net.URISyntaxException | java.io.IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_twtMouseClicked

    private void ytMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ytMouseClicked
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://www.youtube.com/user/kemhan/"));
        } catch (java.net.URISyntaxException | java.io.IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ytMouseClicked

    private void show_pwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_pwMouseClicked
        // TODO add your handling code here:
        char echo = password.getEchoChar();
    
        // Jika echoChar sama dengan karakter yang digunakan untuk menyembunyikan password
        if (echo == '\u25cf') {
            // Set echoChar ke 0 untuk menampilkan karakter password
            password.setEchoChar((char) 0);
        } else {
            // Set echoChar ke karakter yang digunakan untuk menyembunyikan password
            password.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_show_pwMouseClicked

    private void button_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseClicked
        // TODO add your handling code here:
        String sql = "SELECT * FROM admin WHERE username='"+username.getText()+"' AND password='"+password.getText()+"'";
        String a = username.getText();
        String b = password.getText();
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet check = stat.executeQuery(sql);
            
            if(a.equals("") || b.equals("")){
                JOptionPane.showMessageDialog(null, "Masukan Username dan Password!","Terjadi Kesalahan!",JOptionPane.ERROR_MESSAGE);
                reset();
            }else if(check.next() && a.equals(a) && b.equals(b)){
                String nama = check.getString("nama");
                new main_menu().welcome.setText(nama+" !");
                
                if(username.getText().equals(check.getString("username")) && password.getText().equals(check.getString("password"))){
                    new main_menu().setVisible(true);
                    dispose();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Username atau Password Salah","Terjadi Kesalahan!",JOptionPane.ERROR_MESSAGE);
            }
            reset();
            username.requestFocus();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_button_loginMouseClicked

    private void button_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseEntered
        // TODO add your handling code here:
        button_login.setBackground(new Color(54,0,15));
    }//GEN-LAST:event_button_loginMouseEntered

    private void button_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseExited
        // TODO add your handling code here:
        button_login.setBackground(new Color(79,14,40));
    }//GEN-LAST:event_button_loginMouseExited

    private void button_loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMousePressed
        // TODO add your handling code here:
        button_login.setBackground(new Color(28,0,0));
    }//GEN-LAST:event_button_loginMousePressed

    private void button_loginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseReleased
        // TODO add your handling code here:
        button_login.setBackground(new Color(54,0,15));
    }//GEN-LAST:event_button_loginMouseReleased

    private void set_aksesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set_aksesMouseEntered
        // TODO add your handling code here:
        set_akses.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_set_aksesMouseEntered

    private void set_aksesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set_aksesMouseExited
        // TODO add your handling code here:
        set_akses.setForeground(new Color(255,241,241));
    }//GEN-LAST:event_set_aksesMouseExited

    private void forgot_pwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_pwMouseEntered
        // TODO add your handling code here:
        forgot_pw.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_forgot_pwMouseEntered

    private void forgot_pwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_pwMouseExited
        // TODO add your handling code here:
        forgot_pw.setForeground(new Color(255,241,241));
    }//GEN-LAST:event_forgot_pwMouseExited

    private void show_pw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_pw1MouseClicked
        // TODO add your handling code here:
        char echo = change_new_password.getEchoChar();
    
        // Jika echoChar sama dengan karakter yang digunakan untuk menyembunyikan password
        if (echo == '\u25cf') {
            // Set echoChar ke 0 untuk menampilkan karakter password
            change_new_password.setEchoChar((char) 0);
        } else {
            // Set echoChar ke karakter yang digunakan untuk menyembunyikan password
            change_new_password.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_show_pw1MouseClicked

    private void change_pwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_pwMouseClicked
        // TODO add your handling code here:
        String kode_akses = "kemh4n";
        String sql = "SELECT * FROM admin WHERE username = '"+username_forgot.getText()+"'";
        String sql2 = "UPDATE admin SET password = ? WHERE username = ?";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet check = stat.executeQuery(sql);
            
            if(username_forgot.getText().equals("")||change_new_password.getText().equals("")||acc_code.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data!","Terjadi Kesalahan!",JOptionPane.ERROR_MESSAGE);
                reset();
                username_forgot.requestFocus();
            }else{
                if(check.next() && username_forgot.getText().equals(check.getString("username"))){
                    if(acc_code.getText().equals(kode_akses)){
                        PreparedStatement stat2 = conn.prepareStatement(sql2);

                        stat2.setString(1, change_new_password.getText());
                        stat2.setString(2, username_forgot.getText());
                        stat2.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Password Berhasil Diubah, Silahkan Login Kembali");
                        reset();
                        Login();
                    }else{
                        JOptionPane.showMessageDialog(null, "Kode Akses Yang Dimasukan Salah","Terjadi Kesalahan!",JOptionPane.ERROR_MESSAGE);
                        acc_code.setText("");
                        acc_code.requestFocus();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Username Tidak Ditemukan","Terjadi Kesalahan!",JOptionPane.ERROR_MESSAGE);
                    reset();
                    username_forgot.requestFocus();
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah " + e);
            reset();
            username_forgot.requestFocus();
        }

    }//GEN-LAST:event_change_pwMouseClicked

    private void change_pwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_pwMouseEntered
        // TODO add your handling code here:
        change_pw.setBackground(new Color(54,0,15));
    }//GEN-LAST:event_change_pwMouseEntered

    private void change_pwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_pwMouseExited
        // TODO add your handling code here:
        change_pw.setBackground(new Color(79,14,40));
    }//GEN-LAST:event_change_pwMouseExited

    private void change_pwMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_pwMousePressed
        // TODO add your handling code here:
        change_pw.setBackground(new Color(28,0,0));
    }//GEN-LAST:event_change_pwMousePressed

    private void change_pwMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_pwMouseReleased
        // TODO add your handling code here:
        change_pw.setBackground(new Color(54,0,15));
    }//GEN-LAST:event_change_pwMouseReleased

    private void forgot_pwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_pwMouseClicked
        // TODO add your handling code here:
        reset();
        Forgot();
    }//GEN-LAST:event_forgot_pwMouseClicked

    private void back_button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button2MouseEntered
        // TODO add your handling code here:
        forgot_pw.setForeground(new Color(255,241,241));
    }//GEN-LAST:event_back_button2MouseEntered

    private void back_button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button2MouseClicked
        // TODO add your handling code here:
        reset();
        Login();
    }//GEN-LAST:event_back_button2MouseClicked

    private void forgot_pwMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_pwMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_forgot_pwMouseReleased

    private void show_pw2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_pw2MouseClicked
        // TODO add your handling code here:
        char echo = create_new_password.getEchoChar();
    
        // Jika echoChar sama dengan karakter yang digunakan untuk menyembunyikan password
        if (echo == '\u25cf') {
            // Set echoChar ke 0 untuk menampilkan karakter password
            create_new_password.setEchoChar((char) 0);
        } else {
            // Set echoChar ke karakter yang digunakan untuk menyembunyikan password
            create_new_password.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_show_pw2MouseClicked

    private void create_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_buttonMouseClicked
        // TODO add your handling code here:
        //isi koding inti
        String sql = "INSERT INTO admin VALUES (?,?,?)";
        String sql2 = "SELECT * FROM admin WHERE username = '"+new_username.getText()+"'";
        
        String kode_akses = "kemh4n";
        try{
            java.sql.Statement state = conn.createStatement();
            ResultSet check = state.executeQuery(sql2);
            
            if(nama.getText().equals("")||new_username.getText().equals("")||create_new_password.getText().equals("")||create_acc_code.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data!","Terjadi Kesalahan!",JOptionPane.ERROR_MESSAGE);
                reset();
                new_username.requestFocus();
            }else{
                if(create_acc_code.getText().equals(kode_akses)){
                    if(check.next() && new_username.getText().equals(check.getString("username"))){
                        JOptionPane.showMessageDialog(null, "Username Telah Digunakan. Silahkan Gunakan Yang Lain","Terjadi Kesalahan!",JOptionPane.ERROR_MESSAGE);
                        reset();
                        nama.requestFocus();
                    }else{
                        PreparedStatement stat = conn.prepareStatement(sql);
                        stat.setString(1, new_username.getText());
                        stat.setString(2, nama.getText());
                        stat.setString(3, create_new_password.getText());
                        stat.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Data Akses Berhasil Tersimpan, Silahkan Login Kembali");
                        reset();
                        Login();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Kode Akses Yang Dimasukan Salah!","Terjadi Kesalahan!",JOptionPane.ERROR_MESSAGE);
                    create_acc_code.setText("");
                    create_acc_code.requestFocus();
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan " + e);
            reset();
            nama.requestFocus();
        }
    }//GEN-LAST:event_create_buttonMouseClicked

    private void create_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_buttonMouseEntered
        // TODO add your handling code here:
        create_button.setBackground(new Color(54,0,15));
    }//GEN-LAST:event_create_buttonMouseEntered

    private void create_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_buttonMouseExited
        // TODO add your handling code here:
        create_button.setBackground(new Color(79,14,40));
    }//GEN-LAST:event_create_buttonMouseExited

    private void create_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_buttonMousePressed
        // TODO add your handling code here:
        create_button.setBackground(new Color(28,0,0));
    }//GEN-LAST:event_create_buttonMousePressed

    private void create_buttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_buttonMouseReleased
        // TODO add your handling code here:
        create_button.setBackground(new Color(54,0,15));
    }//GEN-LAST:event_create_buttonMouseReleased

    private void set_aksesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set_aksesMouseClicked
        // TODO add your handling code here:
        reset();
        Create();
    }//GEN-LAST:event_set_aksesMouseClicked

    private void back_button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_back_button1MouseEntered

    private void back_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button1MouseClicked
        // TODO add your handling code here:
        reset();
        Login();
    }//GEN-LAST:event_back_button1MouseClicked

    private void set_aksesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set_aksesMouseReleased
        // TODO add your handling code here:
        set_akses.setForeground(new Color(255,241,241));
    }//GEN-LAST:event_set_aksesMouseReleased

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        Close();
    }//GEN-LAST:event_exitMouseClicked

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            button_loginMouseClicked(null);
        }
    }//GEN-LAST:event_passwordKeyPressed

    private void create_acc_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_create_acc_codeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            create_buttonMouseClicked(null);
        }
    }//GEN-LAST:event_create_acc_codeKeyPressed

    private void acc_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acc_codeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            change_pwMouseClicked(null);
        }
    }//GEN-LAST:event_acc_codeKeyPressed

    private void back_button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button3MouseClicked
        // TODO add your handling code here:
        Close();
    }//GEN-LAST:event_back_button3MouseClicked

    private void back_button3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_back_button3MouseEntered

    private void back_button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button4MouseClicked
        // TODO add your handling code here:
        Close();
    }//GEN-LAST:event_back_button4MouseClicked

    private void back_button4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_button4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_back_button4MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acc_code;
    private javax.swing.JPanel area_create;
    private javax.swing.JPanel area_forgot;
    private javax.swing.JPanel area_login;
    private javax.swing.JLabel back_button1;
    private javax.swing.JLabel back_button2;
    private javax.swing.JLabel back_button3;
    private javax.swing.JLabel back_button4;
    private javax.swing.JLabel background;
    private javax.swing.JPanel button_login;
    private javax.swing.JPasswordField change_new_password;
    private javax.swing.JPanel change_pw;
    private javax.swing.JTextField create_acc_code;
    private javax.swing.JPanel create_banner;
    private javax.swing.JPanel create_button;
    private javax.swing.JPasswordField create_new_password;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel forgot_banner;
    private javax.swing.JLabel forgot_pw;
    private javax.swing.JLabel ig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel login_banner;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel main_banner;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField new_username;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel set_akses;
    private javax.swing.JLabel show_pw;
    private javax.swing.JLabel show_pw1;
    private javax.swing.JLabel show_pw2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title10;
    private javax.swing.JLabel title11;
    private javax.swing.JLabel title12;
    private javax.swing.JLabel title13;
    private javax.swing.JLabel title14;
    private javax.swing.JLabel title15;
    private javax.swing.JLabel title16;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JLabel twt;
    private javax.swing.JTextField username;
    private javax.swing.JTextField username_forgot;
    private javax.swing.JLabel web;
    private javax.swing.JLabel yt;
    // End of variables declaration//GEN-END:variables
}
