package Display_running;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Connection.Connection;
import java.io.InputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Khairul Rizki
 */

public class form_data_karyawan extends javax.swing.JFrame {
    
    private DefaultTableModel model;
    private java.sql.Connection conn = new Connection().connect();
    
    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");

    public form_data_karyawan() {
        String Display_running = javax.swing.UIManager.getSystemLookAndFeelClassName();
        try{
            javax.swing.UIManager.setLookAndFeel(Display_running);
        }catch(Exception e){}
        
        initComponents();
        Locale locale = new Locale("ID","id");
        Locale.setDefault(locale);
        datatabel();
    }
    
    protected void datatabel(){
        Object[] baris = {"NIP","Nama","Jenis Kelamin","Pangkat/Golongan","Jabatan"};
        model = new DefaultTableModel(null, baris){
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
        }};
        table_data.setModel(model);
        tanggal_lahir.setDate(new Date());
        
        String sql = "SELECT * FROM db_karyawan ORDER BY nama_lengkap ASC";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            
            while(hasil.next()){
                String a = hasil.getString("nip");
                String b = hasil.getString("nama_lengkap");
                String c = hasil.getString("jenis_kelamin");
                String d = hasil.getString("pangkat");
                String e = hasil.getString("jabatan");
                
                String[] data = {a,b,c,d,e};
                model.addRow(data);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan " + e);
        }
    }

    protected void reset(){
        nip.setText("");
        nama.setText("");
        tempat_lahir.setText("");
        tanggal_lahir.setDate(new Date());
        jk.setSelectedItem("--");
        usia.setValue(0);
        pangkat.setSelectedItem("--");
        jabatan.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        content_panel = new javax.swing.JPanel();
        back_button = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();
        tampil_data = new javax.swing.JPanel();
        content_1 = new javax.swing.JPanel();
        title5 = new javax.swing.JLabel();
        area_search1 = new javax.swing.JPanel();
        search_data = new javax.swing.JTextField();
        b_search_data = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_data = new javax.swing.JTable();
        b_print = new javax.swing.JButton();
        kelola_data = new javax.swing.JPanel();
        content_2 = new javax.swing.JPanel();
        title7 = new javax.swing.JLabel();
        area_form = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nip = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tempat_lahir = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jk = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tanggal_lahir = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        usia = new javax.swing.JSpinner();
        t_simpan = new javax.swing.JButton();
        t_reset = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pangkat = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jabatan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        button_tampil_data = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        button_kelola_data = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Karyawan");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/exit_button.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, -1, -1));

        background.setBackground(new java.awt.Color(79, 14, 14));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/logo_kemhan_small.png"))); // NOI18N

        title6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title6.setForeground(new java.awt.Color(255, 241, 241));
        title6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title6.setText("BALITBANG KEMHAN RI");

        title4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        title4.setForeground(new java.awt.Color(255, 241, 241));
        title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4.setText("Data Karyawan.");

        content_panel.setBackground(new java.awt.Color(255, 241, 241));
        content_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back_button.setBackground(new java.awt.Color(255, 255, 255));
        back_button.setForeground(new java.awt.Color(255, 255, 255));
        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/back_30px.png"))); // NOI18N
        back_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                back_buttonMouseEntered(evt);
            }
        });
        content_panel.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        main_panel.setBackground(new java.awt.Color(187, 135, 96));
        main_panel.setLayout(new java.awt.CardLayout());

        tampil_data.setBackground(new java.awt.Color(187, 135, 96));

        content_1.setBackground(new java.awt.Color(255, 241, 241));

        title5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        title5.setForeground(new java.awt.Color(79, 14, 14));
        title5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title5.setText("Data Karyawan.");

        area_search1.setBackground(new java.awt.Color(255, 241, 241));

        search_data.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        search_data.setForeground(new java.awt.Color(102, 102, 102));
        search_data.setText("Cari");
        search_data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_dataFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_dataFocusLost(evt);
            }
        });
        search_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_dataActionPerformed(evt);
            }
        });
        search_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_dataKeyPressed(evt);
            }
        });

        b_search_data.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/search_20px.png"))); // NOI18N
        b_search_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_search_dataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout area_search1Layout = new javax.swing.GroupLayout(area_search1);
        area_search1.setLayout(area_search1Layout);
        area_search1Layout.setHorizontalGroup(
            area_search1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, area_search1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_data, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_search_data, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        area_search1Layout.setVerticalGroup(
            area_search1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, area_search1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(area_search1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_search_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_data)))
        );

        table_data.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        table_data.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        table_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Jenis Kelamin", "Pangkat", "Jabatan"
            }
        ));
        table_data.setRowHeight(25);
        table_data.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_data.getTableHeader().setResizingAllowed(false);
        table_data.getTableHeader().setReorderingAllowed(false);
        table_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                table_dataMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(table_data);

        b_print.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        b_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/print_25px.png"))); // NOI18N
        b_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_printActionPerformed(evt);
            }
        });

        refresh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/refresh_20px.png"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout content_1Layout = new javax.swing.GroupLayout(content_1);
        content_1.setLayout(content_1Layout);
        content_1Layout.setHorizontalGroup(
            content_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, content_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(content_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, content_1Layout.createSequentialGroup()
                        .addComponent(b_print, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(area_search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        content_1Layout.setVerticalGroup(
            content_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(content_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_print, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(area_search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout tampil_dataLayout = new javax.swing.GroupLayout(tampil_data);
        tampil_data.setLayout(tampil_dataLayout);
        tampil_dataLayout.setHorizontalGroup(
            tampil_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampil_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tampil_dataLayout.setVerticalGroup(
            tampil_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampil_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_panel.add(tampil_data, "card2");

        kelola_data.setBackground(new java.awt.Color(187, 135, 96));

        content_2.setBackground(new java.awt.Color(255, 241, 241));

        title7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        title7.setForeground(new java.awt.Color(79, 14, 14));
        title7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title7.setText("Tambah Data Karyawan.");

        area_form.setBackground(new java.awt.Color(255, 241, 241));

        jPanel1.setBackground(new java.awt.Color(255, 241, 241));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(79, 14, 14));
        jLabel4.setText("NIP");

        nip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nip)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 241, 241));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(79, 14, 14));
        jLabel5.setText("Tempat Lahir");

        tempat_lahir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempat_lahir)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempat_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 241, 241));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 14, 14));
        jLabel6.setText("Jenis Kelamin");

        jk.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Laki - laki", "Perempuan" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 241, 241));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(79, 14, 14));
        jLabel7.setText("Nama Lengkap");

        nama.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 241, 241));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(79, 14, 14));
        jLabel8.setText("Tanggal Lahir");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tanggal_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(tanggal_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 241, 241));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(79, 14, 14));
        jLabel9.setText("Usia");

        usia.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        usia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(usia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t_simpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/save_25px.png"))); // NOI18N
        t_simpan.setText("Simpan");
        t_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_simpanActionPerformed(evt);
            }
        });

        t_reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/reset_20px.png"))); // NOI18N
        t_reset.setText("Reset");
        t_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_resetActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 241, 241));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(79, 14, 14));
        jLabel11.setText("Pangkat/Golongan");

        pangkat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pangkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Kolonel", "Mayor", "Kapten", "Lettu", "Letda", "Letnan Kolonel", "Sersan Mayor", "Pelda", "IV/a", "IV/b", "IV/c", "IV/d", "III/a", "III/b", "III/c", "III/d", "II/a", "II/b", "II/c", "II/d" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pangkat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 241, 241));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(79, 14, 14));
        jLabel12.setText("Jabatan");

        jabatan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout area_formLayout = new javax.swing.GroupLayout(area_form);
        area_form.setLayout(area_formLayout);
        area_formLayout.setHorizontalGroup(
            area_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(area_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(area_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(area_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(area_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        area_formLayout.setVerticalGroup(
            area_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, area_formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(area_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(area_formLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(area_formLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(area_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_reset)
                    .addComponent(t_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(79, 14, 14));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Masukan data diri dibawah dengan lengkap");

        jPanel7.setBackground(new java.awt.Color(79, 14, 14));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout content_2Layout = new javax.swing.GroupLayout(content_2);
        content_2.setLayout(content_2Layout);
        content_2Layout.setHorizontalGroup(
            content_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(content_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(area_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, content_2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(content_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.CENTER))
                .addGap(76, 76, 76))
        );
        content_2Layout.setVerticalGroup(
            content_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(area_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kelola_dataLayout = new javax.swing.GroupLayout(kelola_data);
        kelola_data.setLayout(kelola_dataLayout);
        kelola_dataLayout.setHorizontalGroup(
            kelola_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelola_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kelola_dataLayout.setVerticalGroup(
            kelola_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelola_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_panel.add(kelola_data, "card2");

        content_panel.add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 800, 450));

        button_tampil_data.setBackground(new java.awt.Color(187, 135, 96));
        button_tampil_data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_tampil_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_tampil_dataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_tampil_dataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_tampil_dataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_tampil_dataMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button_tampil_dataMouseReleased(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/show_20px.png"))); // NOI18N
        jLabel2.setText("Tampilkan Data");

        javax.swing.GroupLayout button_tampil_dataLayout = new javax.swing.GroupLayout(button_tampil_data);
        button_tampil_data.setLayout(button_tampil_dataLayout);
        button_tampil_dataLayout.setHorizontalGroup(
            button_tampil_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_tampil_dataLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        button_tampil_dataLayout.setVerticalGroup(
            button_tampil_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_tampil_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content_panel.add(button_tampil_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, -1));

        button_kelola_data.setBackground(new java.awt.Color(187, 135, 96));
        button_kelola_data.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_kelola_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_kelola_dataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_kelola_dataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_kelola_dataMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/add_20px.png"))); // NOI18N
        jLabel3.setText("Tambahkan Data");

        javax.swing.GroupLayout button_kelola_dataLayout = new javax.swing.GroupLayout(button_kelola_data);
        button_kelola_data.setLayout(button_kelola_dataLayout);
        button_kelola_dataLayout.setHorizontalGroup(
            button_kelola_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_kelola_dataLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        button_kelola_dataLayout.setVerticalGroup(
            button_kelola_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_kelola_dataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        content_panel.add(button_kelola_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, -1));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title6)
                    .addComponent(title4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(title6)
                        .addGap(5, 5, 5)
                        .addComponent(title4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar dari aplikasi?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(ok == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseClicked
        // TODO add your handling code here:
        new main_menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_buttonMouseClicked

    private void back_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_buttonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_back_buttonMouseEntered

    private void button_tampil_dataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tampil_dataMouseEntered
        // TODO add your handling code here:
        button_tampil_data.setBackground(new Color(162,110,71));
    }//GEN-LAST:event_button_tampil_dataMouseEntered

    private void button_tampil_dataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tampil_dataMouseExited
        // TODO add your handling code here:
        button_tampil_data.setBackground(new Color(187,135,96));
    }//GEN-LAST:event_button_tampil_dataMouseExited

    private void button_kelola_dataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_kelola_dataMouseEntered
        // TODO add your handling code here:
        button_kelola_data.setBackground(new Color(162,110,71));
    }//GEN-LAST:event_button_kelola_dataMouseEntered

    private void button_kelola_dataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_kelola_dataMouseExited
        // TODO add your handling code here:
        button_kelola_data.setBackground(new Color(187,135,96));
    }//GEN-LAST:event_button_kelola_dataMouseExited

    private void button_tampil_dataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tampil_dataMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_button_tampil_dataMousePressed

    private void button_tampil_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tampil_dataMouseClicked
        // TODO add your handling code here:
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        
        main_panel.add(tampil_data);
        main_panel.repaint();
        main_panel.revalidate();
        datatabel();
    }//GEN-LAST:event_button_tampil_dataMouseClicked

    private void button_tampil_dataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_tampil_dataMouseReleased
        // TODO add your handling code here:
        button_tampil_data.setBackground(new Color(162,110,71));
    }//GEN-LAST:event_button_tampil_dataMouseReleased

    private void button_kelola_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_kelola_dataMouseClicked
        // TODO add your handling code here:
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        
        main_panel.add(kelola_data);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_button_kelola_dataMouseClicked

    private void search_dataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_dataFocusGained
        // TODO add your handling code here:
        String a = "Cari";
        if(search_data.getText().equals(a)){
            search_data.setText("");
        }
        
    }//GEN-LAST:event_search_dataFocusGained

    private void search_dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_dataFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_search_dataFocusLost

    private void b_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_printActionPerformed
        // TODO add your handling code here:
        String realPath = "Image_assets/";
        HashMap hash = new HashMap();
        try {
            hash.put("realPath", realPath);
            InputStream ambil = getClass().getResourceAsStream("/Display_running/report_data_karyawan.jasper") ;
            JasperPrint print = JasperFillManager.fillReport(ambil, hash, conn);
            JasperViewer.viewReport(print, false); 
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Data Gagal Dicetak" + e);
        }
    }//GEN-LAST:event_b_printActionPerformed

    private void search_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_dataActionPerformed

    private void t_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_simpanActionPerformed
        // TODO add your handling code here:
        
        try{
            String sql = "INSERT INTO db_karyawan VALUES (?,?,?,?,?,?,?,?)";
        
            String a = nip.getText();
            String b = nama.getText();
            String c = tempat_lahir.getText();
            String d = df.format(tanggal_lahir.getDate());
            String e = (String) jk.getSelectedItem();
            int f = (int) usia.getValue();
            String g = (String) pangkat.getSelectedItem();
            String h = jabatan.getText();

            if(a.equals("")||b.equals("")||c.equals("")||d.isEmpty()||e.equals("--")||f==0||g.equals("")||h.equals("")){
                JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data Anda.","Terjadi Kesalahan!",JOptionPane.ERROR_MESSAGE);
                reset();
                nip.requestFocus();
            }else{
                try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, a);
                stat.setString(2, b);
                stat.setString(3, c);
                stat.setString(4, d);
                stat.setString(5, e);
                stat.setInt(6, f);
                stat.setString(7, g);
                stat.setString(8, h);
                stat.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data Berhasil Tersimpan");
                reset();
                nip.requestFocus();

                }catch(Exception err){
                    JOptionPane.showMessageDialog(null, "NIP yang Anda Masukan Sudah Ada, Silahkan Coba Lagi.");
                    reset();
                    nip.requestFocus();
                }
            }
        }catch(Exception er){
            JOptionPane.showMessageDialog(null, "error di " + er);
        }
        
    }//GEN-LAST:event_t_simpanActionPerformed

    private void t_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_resetActionPerformed
        // TODO add your handling code here:
        reset();
        nip.requestFocus();
    }//GEN-LAST:event_t_resetActionPerformed

    private void table_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dataMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            edit_data_karyawan f2 = new edit_data_karyawan();
        
            int bar = table_data.getSelectedRow();
            String nip = model.getValueAt(bar, 0).toString();
            String nama = model.getValueAt(bar, 1).toString();
            String jenis_kelamin = model.getValueAt(bar, 2).toString();
            String pangkat = model.getValueAt(bar, 3).toString();
            String jabatan = model.getValueAt(bar, 4).toString();

            f2.nip.setText(nip);
            f2.nama.setText(nama);
            f2.jk.setSelectedItem(jenis_kelamin);
            f2.pangkat.setSelectedItem(pangkat);
            f2.jabatan.setText(jabatan);

            String sql = "SELECT * FROM db_karyawan WHERE nip = '"+nip+"'";

            try{
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while(hasil.next()){
                    String tempat_lahir = hasil.getString("tl");
                    Date tgl = hasil.getDate("ttl");
                    int usia = hasil.getInt("usia");
                    f2.usia.setValue(usia);
                    f2.tempat_lahir.setText(tempat_lahir);
                    f2.tanggal_lahir.setDate(tgl);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan " + e);
            }

            
            f2.setVisible(true);
            f2.pack();
            f2.setDefaultCloseOperation(form_data_karyawan.DISPOSE_ON_CLOSE);
        }
        
    }//GEN-LAST:event_table_dataMouseClicked

    private void table_dataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_table_dataMouseEntered

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        datatabel();
        search_data.setText("Cari");
    }//GEN-LAST:event_refreshActionPerformed

    private void b_search_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_search_dataActionPerformed
        // TODO add your handling code here:
        if(search_data.getText().equals("Cari") || search_data.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukan Kata Kunci");
            datatabel();
        }else{
            Object[] baris = {"NIP","Nama","Jenis Kelamin","Pangkat/Golongan","Jabatan"};
            model = new DefaultTableModel(null, baris){
                @Override
                public boolean isCellEditable(int row, int column) {
                return false;
            }};
            table_data.setModel(model);
            String sql = "SELECT * FROM db_karyawan WHERE nip like '%"+search_data.getText()+"%' OR nama_lengkap like '%"+search_data.getText()+"%' OR pangkat like '%"+search_data.getText()+"%' OR jabatan like '%"+search_data.getText()+"%' ORDER BY nama_lengkap ASC";
            try{
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);

                while(hasil.next()){
                String a = hasil.getString("nip");
                String b = hasil.getString("nama_lengkap");
                String c = hasil.getString("jenis_kelamin");
                String d = hasil.getString("pangkat");
                String e = hasil.getString("jabatan");
                
                String[] data = {a,b,c,d,e};
                model.addRow(data);
            }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemulan " + e);
                }
            }
    }//GEN-LAST:event_b_search_dataActionPerformed

    private void search_dataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_dataKeyPressed
        // TODO add your handling code here:
        String a = search_data.getText();
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(a.equals("Cari")||a.equals("")){
                JOptionPane.showMessageDialog(null, "Silahkan Masukan Pencarian Anda.","Terjadi Kesalahan!",JOptionPane.ERROR_MESSAGE);
                search_data.setText("Cari");
            }else{
                b_search_dataActionPerformed(null);
            }
        }
    }//GEN-LAST:event_search_dataKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_data_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_data_karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel area_form;
    private javax.swing.JPanel area_search1;
    private javax.swing.JButton b_print;
    private javax.swing.JButton b_search_data;
    private javax.swing.JLabel back_button;
    private javax.swing.JPanel background;
    private javax.swing.JPanel button_kelola_data;
    private javax.swing.JPanel button_tampil_data;
    private javax.swing.JPanel content_1;
    private javax.swing.JPanel content_2;
    private javax.swing.JPanel content_panel;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jabatan;
    private javax.swing.JComboBox<String> jk;
    private javax.swing.JPanel kelola_data;
    private javax.swing.JPanel main_panel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nip;
    private javax.swing.JComboBox<String> pangkat;
    public static final javax.swing.JButton refresh = new javax.swing.JButton();
    private javax.swing.JTextField search_data;
    private javax.swing.JButton t_reset;
    private javax.swing.JButton t_simpan;
    private javax.swing.JTable table_data;
    private javax.swing.JPanel tampil_data;
    private com.toedter.calendar.JDateChooser tanggal_lahir;
    private javax.swing.JTextField tempat_lahir;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JSpinner usia;
    // End of variables declaration//GEN-END:variables

    void refreshMouseClicked(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
