package Display_running;

import java.awt.Color;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.Clock;
import java.util.Locale;
import javax.swing.JOptionPane;
/**
 *
 * @author Khairul Rizki
 */
public class main_menu extends javax.swing.JFrame {

    /**
     * Creates new form main_menu
     */
    public main_menu() {
        String Display_running = javax.swing.UIManager.getSystemLookAndFeelClassName();
        try{
            javax.swing.UIManager.setLookAndFeel(Display_running);
        }catch(Exception e){}
        
        initComponents();
        Locale locale = new Locale("ID","id");
        Locale.setDefault(locale);
        tanggal();
        menu_hasil.setEnabled(false);
    }
    
    protected void tanggal(){
        Date tanggal = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEEE, dd MMMMM yyyy");
        String tanggalFormatted = dateFormat.format(tanggal);
        date.setText(tanggalFormatted);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        menu_set = new javax.swing.JPanel();
        menu_data_karyawan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menu_penilaian = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menu_kriteria = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menu_keputusan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menu_hasil = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hover = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(79, 14, 14));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/logo_kemhan_small.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        title6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title6.setForeground(new java.awt.Color(255, 241, 241));
        title6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title6.setText("BALITBANG KEMHAN RI");
        background.add(title6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        title4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        title4.setForeground(new java.awt.Color(255, 241, 241));
        title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4.setText("Dashboard.");
        background.add(title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/exit_button.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        background.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, -1, -1));

        content.setBackground(new java.awt.Color(255, 241, 241));

        sd.setBackground(new java.awt.Color(79, 14, 14));
        sd.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        sd.setForeground(new java.awt.Color(79, 14, 14));
        sd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sd.setText("Selamat Datang");

        date.setBackground(new java.awt.Color(79, 14, 14));
        date.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(79, 14, 14));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("XX/XX/XXXX");

        menu_set.setBackground(new java.awt.Color(255, 241, 241));
        menu_set.setPreferredSize(new java.awt.Dimension(440, 350));
        menu_set.setLayout(null);

        menu_data_karyawan.setBackground(new java.awt.Color(187, 135, 96));
        menu_data_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_data_karyawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_data_karyawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_data_karyawanMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/icon_karyawan.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(79, 14, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Karyawan");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout menu_data_karyawanLayout = new javax.swing.GroupLayout(menu_data_karyawan);
        menu_data_karyawan.setLayout(menu_data_karyawanLayout);
        menu_data_karyawanLayout.setHorizontalGroup(
            menu_data_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addGroup(menu_data_karyawanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_data_karyawanLayout.setVerticalGroup(
            menu_data_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_data_karyawanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        menu_set.add(menu_data_karyawan);
        menu_data_karyawan.setBounds(10, 21, 120, 120);

        menu_penilaian.setBackground(new java.awt.Color(187, 135, 96));
        menu_penilaian.setPreferredSize(new java.awt.Dimension(150, 134));
        menu_penilaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_penilaianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_penilaianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_penilaianMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/icon_penilaian.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(79, 14, 14));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Penilaian Karyawan");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout menu_penilaianLayout = new javax.swing.GroupLayout(menu_penilaian);
        menu_penilaian.setLayout(menu_penilaianLayout);
        menu_penilaianLayout.setHorizontalGroup(
            menu_penilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menu_penilaianLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_penilaianLayout.setVerticalGroup(
            menu_penilaianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_penilaianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        menu_set.add(menu_penilaian);
        menu_penilaian.setBounds(140, 20, 160, 120);

        menu_kriteria.setBackground(new java.awt.Color(187, 135, 96));
        menu_kriteria.setPreferredSize(new java.awt.Dimension(150, 134));
        menu_kriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_kriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_kriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_kriteriaMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/icon_kriteria.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(79, 14, 14));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Kriteria Mutasi");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout menu_kriteriaLayout = new javax.swing.GroupLayout(menu_kriteria);
        menu_kriteria.setLayout(menu_kriteriaLayout);
        menu_kriteriaLayout.setHorizontalGroup(
            menu_kriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menu_kriteriaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_kriteriaLayout.setVerticalGroup(
            menu_kriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_kriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        menu_set.add(menu_kriteria);
        menu_kriteria.setBounds(170, 150, 130, 130);

        menu_keputusan.setBackground(new java.awt.Color(187, 135, 96));
        menu_keputusan.setPreferredSize(new java.awt.Dimension(150, 134));
        menu_keputusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_keputusanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_keputusanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_keputusanMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/icon_keputusan.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(79, 14, 14));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Keputusan Mutasi");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout menu_keputusanLayout = new javax.swing.GroupLayout(menu_keputusan);
        menu_keputusan.setLayout(menu_keputusanLayout);
        menu_keputusanLayout.setHorizontalGroup(
            menu_keputusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menu_keputusanLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_keputusanLayout.setVerticalGroup(
            menu_keputusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_keputusanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        menu_set.add(menu_keputusan);
        menu_keputusan.setBounds(10, 150, 150, 130);

        menu_hasil.setBackground(new java.awt.Color(187, 135, 96));
        menu_hasil.setPreferredSize(new java.awt.Dimension(150, 134));
        menu_hasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_hasilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_hasilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_hasilMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/icon_hasil.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(79, 14, 14));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Hasil Mutasi");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout menu_hasilLayout = new javax.swing.GroupLayout(menu_hasil);
        menu_hasil.setLayout(menu_hasilLayout);
        menu_hasilLayout.setHorizontalGroup(
            menu_hasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menu_hasilLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menu_hasilLayout.setVerticalGroup(
            menu_hasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_hasilLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        menu_set.add(menu_hasil);
        menu_hasil.setBounds(310, 20, 124, 260);

        hover.setBackground(new java.awt.Color(255, 241, 241));
        hover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/logout.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(79, 14, 14));
        jLabel12.setText("Logout");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout hoverLayout = new javax.swing.GroupLayout(hover);
        hover.setLayout(hoverLayout);
        hoverLayout.setHorizontalGroup(
            hoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        hoverLayout.setVerticalGroup(
            hoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 241, 241));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_assets/about.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 13, Short.MAX_VALUE)))
        );

        welcome.setBackground(new java.awt.Color(79, 14, 14));
        welcome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(79, 14, 14));
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addComponent(sd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(menu_set, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(menu_set, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, -1, 470));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_data_karyawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_data_karyawanMouseEntered
        // TODO add your handling code here:
        menu_data_karyawan.setBackground(new Color(162,110,71));
    }//GEN-LAST:event_menu_data_karyawanMouseEntered

    private void menu_penilaianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_penilaianMouseEntered
        // TODO add your handling code here:
        menu_penilaian.setBackground(new Color(162,110,71));
    }//GEN-LAST:event_menu_penilaianMouseEntered

    private void menu_keputusanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_keputusanMouseEntered
        // TODO add your handling code here:
        menu_keputusan.setBackground(new Color(162,110,71));
    }//GEN-LAST:event_menu_keputusanMouseEntered

    private void menu_kriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_kriteriaMouseEntered
        // TODO add your handling code here:
        menu_kriteria.setBackground(new Color(162,110,71));
    }//GEN-LAST:event_menu_kriteriaMouseEntered

    private void menu_hasilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_hasilMouseEntered
        // TODO add your handling code here:
        menu_hasil.setBackground(new Color(162,110,71));
    }//GEN-LAST:event_menu_hasilMouseEntered

    private void menu_data_karyawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_data_karyawanMouseExited
        // TODO add your handling code here:
        menu_data_karyawan.setBackground(new Color(187,135,96));
    }//GEN-LAST:event_menu_data_karyawanMouseExited

    private void menu_penilaianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_penilaianMouseExited
        // TODO add your handling code here:
        menu_penilaian.setBackground(new Color(187,135,96));
    }//GEN-LAST:event_menu_penilaianMouseExited

    private void menu_keputusanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_keputusanMouseExited
        // TODO add your handling code here:
        menu_keputusan.setBackground(new Color(187,135,96));
    }//GEN-LAST:event_menu_keputusanMouseExited

    private void menu_kriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_kriteriaMouseExited
        // TODO add your handling code here:
        menu_kriteria.setBackground(new Color(187,135,96));
    }//GEN-LAST:event_menu_kriteriaMouseExited

    private void menu_hasilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_hasilMouseExited
        // TODO add your handling code here:
        menu_hasil.setBackground(new Color(187,135,96));
    }//GEN-LAST:event_menu_hasilMouseExited

    private void hoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverMouseEntered
        // TODO add your handling code here:
        hover.setBackground(new Color(230,216,216));
    }//GEN-LAST:event_hoverMouseEntered

    private void hoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverMouseExited
        // TODO add your handling code here:
        hover.setBackground(new Color(255,241,241));
    }//GEN-LAST:event_hoverMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar dari aplikasi?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(ok == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void hoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverMouseClicked
        // TODO add your handling code here:
        new form_login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hoverMouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        jPanel1.setBackground(new Color(230,216,216));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        jPanel1.setBackground(new Color(255,241,241));
    }//GEN-LAST:event_jPanel1MouseExited

    private void menu_data_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_data_karyawanMouseClicked
        // TODO add your handling code here:
        new form_data_karyawan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_data_karyawanMouseClicked

    private void menu_kriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_kriteriaMouseClicked
        // TODO add your handling code here:
        new form_kriteria().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_kriteriaMouseClicked

    private void menu_penilaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_penilaianMouseClicked
        // TODO add your handling code here:
        new form_penilaian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_penilaianMouseClicked

    private void menu_keputusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_keputusanMouseClicked
        // TODO add your handling code here:
        new form_keputusan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_keputusanMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        new info_aplikasi().setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void menu_hasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_hasilMouseClicked
        // TODO add your handling code here:
        new form_hasil().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_hasilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel content;
    private javax.swing.JLabel date;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel hover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu_data_karyawan;
    private javax.swing.JPanel menu_hasil;
    private javax.swing.JPanel menu_keputusan;
    private javax.swing.JPanel menu_kriteria;
    private javax.swing.JPanel menu_penilaian;
    private javax.swing.JPanel menu_set;
    public static final javax.swing.JLabel sd = new javax.swing.JLabel();
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title6;
    public static final javax.swing.JLabel welcome = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
